### ISSUE TITLE
Connection Times Out Trying to Delete Transform

### ISSUE THREAD

**Issue by drproteus** [Aloomaio/alooma-python#117]
```
>>> client.delete_transform("foo")
Traceback (most recent call last):
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='app.alooma.com', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/alooma/alooma.py", line 686, in delete_transform
    return self.__send_request(requests.delete, url)
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/alooma/alooma.py", line 111, in __send_request
    response = func(url, **params)
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/requests/api.py", line 158, in delete
    return request('delete', url, **kwargs)
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/code-engine-env/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='app.alooma.com', port=443): Read timed out. (read timeout=60)
```

I'm able to `set_code_engine_code` but not delete it. Is there any other simpler way to go about making sure my code engine doesn't get littered with orphaned modules as time goes one?

**Comment by oxmane** [comment]
Hi @drproteus 
Thanks for reporting the issue.
We've identified the problem, and are working on a fix.
We expect a fix to be deployed next week.
I'll update here once it is fixed.

**Comment by oxmane** [comment]
Hi @drproteus 
The issue should be resolved now.
I'm gonna go ahead and close this.
