### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Client'

### ISSUE THREAD

**Issue by yassineaboukir** [Aloomaio/alooma-python#119]
Hi,

I am running into this issue:

```python
Traceback (most recent call last):
  File "alooma.py", line 1, in <module>
    import alooma
  File "/root/alooma.py", line 6, in <module>
    api = alooma.Client(api_key=API_KEY, hostname=ACCOUNT_NAME)
AttributeError: 'module' object has no attribute 'Client'
```

This is my python code:
```python
import alooma
API_KEY = "SECRET" # example
ACCOUNT_NAME = "SECRET" 

api = alooma.Client(api_key=API_KEY, ACCOUNT_NAME=ACCOUNT_NAME)
INPUT_NAME = 'TestInput'
input_data = api.get_input_by_name(INPUT_NAME)[0]
```

Tried on both: `Python 2.7.16` and `Python 3.7.3`.

Any idea what might be the root-cause of this issue?

Regards.

**Comment by tme5** [comment]
try relative import
import .alooma

or go for absolute import
import alooma.alooma

**Comment by s0phr0syn3** [comment]
@yassineaboukir I ran into the same issue and figured out it was caused by me naming my script `alooma.py`, which conflicts with the installed package `alooma` since that package also  contains a file named `alooma.py`. The error is caused by Python trying to import your `alooma.py` as a package, which of course doesn't define any `Client` method or class.

Renaming the script file to literally anything else resolved the issue for me.
